name: inventario

services:
  development:
    build: ./
    volumes:
      - type: bind
        source: ../
        target: /src
    depends_on:
      - mongo
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
